name: formatter

on:
  push:
    paths:
      - "scripts/**"
      - ".github/workflows/format.yml"
  pull_request:
    paths:
      - "scripts/**"
      - ".github/workflows/format.yml"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
